language: node_js
node_js:
- '6'
branches:
  only:
  - master
install:
- npm install -g gitbook-cli
before_script:
- gitbook install
script:
- gitbook build
after_success:
- cd _book
- git config --global user.name 'wangyf'
- git config --global user.email 'zgtjwyftc@gmail.com'
- git init
- git add .
- git commit -m "Deploy to GitHub Pages"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
env:
  global:
  - GH_REF: github.com/MasterStudio/MasterWechatApp.git
  - secure: eqtwP2cKp5t/DIgZKszjm1GzHpnLSwyybyRliVk0ajSRxhlw8EvihAlwtEboeTYPWBEw763HG7hBFWNrGaK6EqICeZBEkYmvVPCMpzDwl8Yx9FPdctGaaddlGPRAv7v0InSt9xFQwBv5l8ZSHZOwRErM081ucqBvaFJTBOWbQawcGMHbsP3zuCz04T4JidXM622aWITFufBvpefiNUozbCPJV2ppr+8j3EllAF7nwhfM+GXGisry+W3SnY0a5YLULplaYGYL5bXtdD/+pEG5gpUfNb/NIIUQAy/iLsXC/5ncDgwbNR+DBon8lxkFDqUMtV7r26JpWDlKEx1oTA0uiWl8/jZ32Aqgdfexz0/YaIMeSvywwnzYZPONavD3kBBPYmBJkaIknnEP0cafscpXKmcNzbU27imOUdd5r3E2w6mVycVG0Y0tisgVqqJGwTnKN5U2YuYTsgQ/Wh3yrMvROlbiL6FLA0EYYKkBF2tiW3dY7ryGdW2jlZQ8QWrUS+OWhuYwWFTInNND3apcbHg7GmvyFC68uRfGz5bkoVD6cyPcxvLR6zR/5VR50GKlhU2RTfkKHj+WJU42sc2sXgRo5bBWix1yZ8zf2Y54DFtjkoW0kR7erJEgHylroPlWx69XoQDA9R8Q8D65RGIqIwnUgtwbnIQAKuh5GNOYc4G1Dyo=
